name: VCam Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install dependencies
        run: npm install

      - name: Create Cypress environment file
        run: |
          echo '{
            "credentials": {
              "email": "test@example.com",
              "password": "password"
            }
          }' > cypress.env.json

      - name: Run Cypress tests
        run: npx cypress run
